version: 0.2
# 1. Generates the SAM template in preparation of Lambda stack update.
# 2. Deploys the Bot UI web page to S3.
# Requires environment variables to be defined, such as ARTIFACT_BUCKET, WEBSITE_BUCKET, etc.

env:

  variables:
    JS_CONFIG_FILE : "botui/js/config.js"
    TEST_USER_NAME : "user10"
    # environment variables required from the build project:
    #  ARTIFACT_BUCKET
    #  WEBSITE_BUCKET
    #  REGION
    #  IDENTITY_POOL_ID
    #  USER_POOL_ID
    #  USER_POOL_CLIENT_ID
    #  API_URL
    #  TEST_USER_SECRET_ID

phases:

  install:
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - cp ./botui/js/config.js.template ./botui/js/config.js

  pre_build:
    commands:
      - echo "Setting up test user"
      - chmod +x ./codebuild/setup-test-user-config.sh
      - ./codebuild/setup-test-user-config.sh

  build:
    commands:
      - echo "Generating CloudFormation template from API SAM template..."
      - aws cloudformation package --template-file cloudformation/multilanguage-api.yaml --s3-bucket ${ARTIFACT_BUCKET}
                                   --output-template-file multilanguage-api-deployable.yaml
      - echo "Deploying S3 website..."
      - aws s3 sync --acl public-read --delete ./botui/ s3://${WEBSITE_BUCKET}/botui/
      - aws s3 cp --acl public-read ./botui/favicon.ico s3://${WEBSITE_BUCKET}/favicon.ico
      # TODO, perhapse makes better sense to separate into 2-phase deploment activities?
      # Website deploy, followed by API deploy, or vise-versa, or parallel?

artifacts:

  type: zip
  files:
    - multilanguage-api-deployable.yaml
