version: 0.2

env:
  variables:
    # Adjust these to your environment.
    CFN_ARTIFACT_BUCKET: "codepipeline-sandbox01-iad"
    BOTUI_BUCKET_NAME: "www.sandbox01.demolab.host"
    # BOTUI_S3_URL: "s3://www.sandbox01.demolab.host/botui/"

phases:
  install:
    commands:
      # generate the SAM Template
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ${CFN_ARTIFACT_BUCKET}
                                   --output-template-file outputSamTemplate.yaml
      # deploy the Bot UI web page 
      # TODO it would be more sensible to first update the service itself, followed by this UI. 
      - aws s3 sync --acl public-read --delete ./botui/ s3://${BOTUI_BUCKET_NAME}/botui/
      - aws s3 put --acl public-read ./botui/favicon.ico s3://${BOTUI_BUCKET_NAME}/favicon.ico
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml
