AWSTemplateFormatVersion: '2010-09-09'
Description: Multilanguage Bot top level stack

Parameters: 

  CognitoStackName:
    Description: FOO
    Type: String
    AllowedPattern : "^[a-zA-Z][a-zA-Z0-9]*$"

Resources:

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AWS CloudFormation Stack Parameters
      Tags:
        - MultilanguageBot
      TemplateURL: https://s3.amazonaws.com/.../TemplateName.extension
      TimeoutInMinutes: 3  

Outputs:
  BotUrl:
    Value: !Ref FOO
