AWSTemplateFormatVersion: '2010-09-09'
Description: Multilanguage Bot top level stack

Metadata:
  # Group the parameters for pretty CloudFormation console GUI. 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      -
        Label:
          default: "Edge Stack"
        Parameters:
          - DomainName
          - FullDomainName
          - AcmCertificateArn
          - BotApiEndpoint
      -
        Label:
          default: "Cognito Stack"
        Parameters:
          - TestUserEmail
      -
        Label:
          default: "Pipeline Stack"
        Parameters:
          - GitHubRepo
          - GitHubUser
          - GitHubBranch

Parameters: 

  # Cognito params
  TestUserEmail:
    Description: Test email address for activation of the Cognito test user,. 
      Its for the demo web app. A temp password is sent to this email for user confirmation.
    Type: String

  # Edge website parameters
  DomainName:
    Description: Domain name of your existing Amazon Route53 hosted zone. E.g. "example.com".
    Type: String   
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid Route53 hosted zone within your account.
  FullDomainName:
    Description: Desired DNS endpoint name for the bot endpoint.
        This creates a Route53 A Record within the DNS zone. E.g. "flowers.example.com"
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS name for the website.
  AcmCertificateArn:
    Description: the Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
    Type: String
    AllowedPattern: "arn:aws:acm:.*"
  BotApiEndpoint:
    # At resource creation, we won't know where the endpoint is in advance, 
    # Since the downstream pipeline will deploy the actual Bot SAM template.
    # So at this early point, use a dummy origin as a temporary placeholder.
    # TODO automate the update of the CFN stack parameter by downstream step, 
    # e.g. Check if default, then set actual endpoint using CodeBuild AWS CLI.
    Description: Bot API regional endpoint. E.g. ".*execute-api.*amazonaws.com/Prod/MultilanguageBot"
    Default: "www.amazonaws.com/"
    Type: String
    AllowedPattern: ".*amazonaws.com.*/"

   # Pipeline parameters
  GitHubRepo:
    Description: Name of your forked Github repo for this project. E.g. "MultilanguageBot"
    Type: String
  GitHubUser:
    Description: Your Github username. 
        The Pipeline will connect using the OAuth token, which you should have stored in SecretsManager.
    Type: String
  GitHubBranch:
    Type: String
    Default: 'master'

Resources:

  Cognito:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/multilanguage-bot/cloudformation/cognito.yaml
      TimeoutInMinutes: 3
      Parameters:
        TestUserEmail: !Ref TestUserEmail

  Edge:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/multilanguage-bot/cloudformation/edge-site.yaml
      TimeoutInMinutes: 45 # CloudFront distribution creation will take time
      Parameters:
        DomainName: !Ref DomainName
        FullDomainName: !Ref FullDomainName
        AcmCertificateArn: !Ref AcmCertificateArn
        BotApiEndpoint: !Ref BotApiEndpoint

  Pipeline:
    DependsOn:
      - Cognito
      - Edge
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/multilanguage-bot/cloudformation/pipeline.yaml
      TimeoutInMinutes: 10
      Parameters:
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        GitHubUser: !Ref GitHubUser
        WebsiteBucket: !GetAtt [Edge, Outputs.BucketName]
        IdentityPoolId: !GetAtt [Cognito, Outputs.IdentityPoolId]
        UserPoolId:  !GetAtt [Cognito, Outputs.UserPoolId]
        UserPoolClientID: !GetAtt [Cognito, Outputs.UserPoolClientId]
        ApiUrl: !Sub https://${FullDomainName}/Test/MultilanguageBot
        BotApiStackName: !Sub ${AWS::StackName}Bot
        CognitoStackName: !GetAtt [Cognito, Outputs.StackName]
        FrontDistribution: !GetAtt [Edge, Outputs.Distribution]
Outputs:
  UserPoolId:
    Value: !GetAtt [Cognito, Outputs.UserPoolId]
  UserPoolId:
    Value: !GetAtt [Cognito, Outputs.UserPoolId]
  UserPoolClientId:
    Value: !GetAtt [Cognito, Outputs.UserPoolClientId]
  IdentityPoolId:
    Value: !GetAtt [Cognito, Outputs.IdentityPoolId]
  BucketName:
    Value: !GetAtt [Edge, Outputs.BucketName]
  DomainName:
    Value: !GetAtt [Edge, Outputs.DomainName]
  DebugCognitoStack:
    Value: !Ref Cognito