AWSTemplateFormatVersion: '2010-09-09'
Description: Multilanguage Bot top level stack

Parameters: 

  TestUserEmail:
    Description: Test email address for activation of the Cognito test user,. 
      Its for the demo web app. A temp password is sent to this email for user confirmation.
    Type: String

Resources:

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/multilanguage-bot/cognito/cognito-cfn.yaml
      Parameters:
        TestUserEmail: !Ref TestUserEmail
      TimeoutInMinutes: 3  

Outputs:
  CognitoThing:
    Value: !Ref CognitoStack
